"""Register explicit file options through Typer's public command extension.

Examples:
    ```python
    from judgevet.adapters.inbound.cli_options import FileInputs

    assert FileInputs().evidence is None
    ```

See Also:
    - [judgevet.adapters.inbound.cli][]: Command factory.
    - [judgevet.adapters.inbound.cli_media][]: Evidence file validation.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Literal, TypedDict, Unpack

import typer
from typer.core import TyperArgument, TyperCommand, TyperOption


@dataclass(frozen=True)
class FileInputs:
    """Group optional policy and evidence paths for internal dispatch.

    Attributes:
        policy (str | None): Explicit policy path.
        evidence (str | None): Explicit image manifest path.

    Examples:
        ```python
        assert FileInputs().policy is None
        ```
    """

    policy: str | None = None
    evidence: str | None = None


class CommandOptions(TypedDict, total=False):
    """Describe the public Typer command constructor keyword options.

    Attributes:
        context_settings (dict): Context construction settings.
        callback (Callable): Command callback.
        help (str): Full command help.
        epilog (str): Help epilog.
        short_help (str): Short help.
        options_metavar (str): Option placeholder.
        add_help_option (bool): Enable help option.
        no_args_is_help (bool): Show help without arguments.
        hidden (bool): Hide command.
        deprecated (bool): Mark deprecated command.
        rich_markup_mode (str): Help markup selection.
        rich_help_panel (str): Rich help panel.
    """

    context_settings: dict[str, object] | None
    callback: Callable[..., object] | None
    help: str | None
    epilog: str | None
    short_help: str | None
    options_metavar: str | None
    add_help_option: bool
    no_args_is_help: bool
    hidden: bool
    deprecated: bool
    rich_markup_mode: Literal["markdown", "rich"] | None
    rich_help_panel: str | None


def _store_option(ctx: object, param: object, value: object) -> None:
    """Keep file option occurrences in invocation metadata.

    Args:
        ctx: Public Typer invocation context.
        param: Registered file option.
        value: Parsed repeated string values.

    Raises:
        TypeError: Typer supplies unexpected callback objects.
    """
    if (
        not isinstance(ctx, typer.Context)
        or not isinstance(param, TyperOption)
        or not isinstance(param.name, str)
    ):
        raise TypeError("Expected a Typer context and option")
    ctx.meta[param.name] = value


def file_values(ctx: typer.Context, name: str) -> list[str]:
    """Retrieve typed option occurrences without using provider selection storage.

    Args:
        ctx: Current invocation context.
        name: Registered option name.

    Returns:
        Ordered string values, empty when the option is absent.

    Raises:
        TypeError: Invocation metadata contains an unexpected value.
    """
    values = ctx.meta.get(name, ())
    if not isinstance(values, tuple) or not all(isinstance(v, str) for v in values):
        raise TypeError("Invalid file option metadata")
    return list(values)


class FileCommand(TyperCommand):
    """Add explicit file options while retaining the ordinary callback signature.

    Attributes:
        context_class (type): Public Typer context for metadata and provider choice.

    Examples:
        ```python
        assert FileCommand.context_class is typer.Context
        ```
    """

    context_class = typer.Context

    def __init__(
        self,
        name: str | None,
        *,
        params: list[TyperArgument | TyperOption] | None = None,
        **kwargs: Unpack[CommandOptions],
    ) -> None:
        """Register repeated options so command validation can diagnose duplicates.

        Args:
            name: Command name.
            params: Callback parameters generated by Typer.

        Other Parameters:
            **kwargs: Public command constructor options.
        """
        descriptions = {
            "--state-file": "Read UTF-8 state from a file; - reads stdin",
            "--questions-file": "Read questions from a UTF-8 JSON file",
            "--policy": "Apply an explicit acceptance policy from JSON",
            "--evidence-file": "Read an image evidence manifest from UTF-8 JSON",
        }
        options = [
            TyperOption(
                param_decls=[flag],
                multiple=True,
                expose_value=False,
                callback=_store_option,
                help=help_text,
            )
            for flag, help_text in descriptions.items()
        ]
        super().__init__(name, params=[*(params or []), *options], **kwargs)
